#!/bin/python

import os
import sys
import io

## Still Left to do:
## Environ, Help, Echo(partial implementation started), DIR (displaying file in directory require)
## 2. Check assignment but it appears to deal with executing programs
## 3. Take commandline input from a file 

pwd = os.getcwd()
prompt = pwd + '$ '

def builtin_clear():
    os.system('cls' if os.name == 'nt' else 'clear')

def builtin_chdir(path):
    global pwd
    if path == None:
        print(pwd)
    else:
        try:
            os.chdir(path)
            pwd = path
        except OSError as e:
            print(e, file=sys.stderr)

def builtin_dir(path):
    try:
        contents = os.listdir(path)
        contents.sort()
        for f in contents:
            print(f)
    except OSError as e:
        print(e, file=sys.stderr)

def builtin_echo(txt):
    if txt is not None:
        print(txt)

def builtin_pause():
    sys.stdin.read(1)

def builtin_pwd():
    print(pwd)

while(True):
    command = input(prompt)
    args = command.split(' ', 1)
    cmdargs = args[1] if len(args) > 1 else None

    if args[0] == "exit":
        sys.exit()
    if args[0] == "dir":
        builtin_dir(cmdargs)
    if args[0] == "cd":
        builtin_chdir(cmdargs)
    if args[0] == "clr":
        builtin_clear()
    if args[0] == "pause":
        builtin_pause()
    if args[0] == "echo":
        builtin_echo(cmdargs)
